### ISSUE TITLE
Improving isRequired validation

### ISSUE THREAD

**Issue by awnigharbia** [ganeshrvel/pub-rules#1]
If the user has entered multiple empty lines with textField it'll consider it as non-empty value. so please make sure this behavior  added to the `isRequired` property.

**Comment by ganeshrvel** [comment]
@awnigharbia will look into this. thanks for reporting

**Comment by ganeshrvel** [comment]
@awnigharbia I wasn't been able to reproduce the issue. it works just as intended! could you confirm?

**Comment by awnigharbia** [comment]
Actually tested and still not working. if I added just spaces in the text field it'll consider it a text but it's an empty state.

**Comment by girish54321** [comment]
@awnigharbia yes this is an issues but can be fixed very easily right @ganeshrvel  ?  :-)

**Comment by ganeshrvel** [comment]
@awnigharbia @girish54321 can someone send me a code snippet, gist or a codepen? I am not able to reproduce this issue.
I should be able to fix this asap

**Comment by girish54321** [comment]
@awnigharbia  sure will send you code snippet in some time.

**Comment by ganeshrvel** [comment]
@awnigharbia @girish54321 

I have added `options` feature in **rules: 1.2.0+1**

Please see if this code work for you guys
```dart
import 'package:rules/src/models/rule_options.dart';

final inputValue =  '         ';
final rule = Rule(
      inputValue,
      name: 'Some field value',
      isRequired: true,
      customErrorText: 'Invalid value',
      options: RuleOptions(
        trim: true,
      ),
);


print(rule.hasError);
````

**Comment by awnigharbia** [comment]
@ganeshrvel  This was my point. Thanks for your input!
