### ISSUE TITLE
caseSensitive

### ISSUE THREAD

**Issue by mbfakourii** [ganeshrvel/pub-rules#2]
hi how set caseSensitive in regex ?

**Comment by ganeshrvel** [comment]
I will fix the regex implementation

**Comment by ganeshrvel** [comment]
You may update the rules package to 1.1.0. 
Note: Breaking changes: regex option now expects a RegExp object.

PS: Looks like regex was always case sensitive

**Comment by mbfakourii** [comment]
thanks its work
